#!/usr/bin/env bash
# Generate dependency graph, symbols, tests, and call flow data for a Rust crate.
# Usage: ./scripts/crate-map.sh <crate-dir>
# Example: ./scripts/crate-map.sh codex-rs/core
#
# Output: markdown suitable for embedding in CLAUDE.md

set -euo pipefail

CRATE_DIR="${1:?Usage: crate-map.sh <crate-dir>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CRATE_PATH="$REPO_ROOT/$CRATE_DIR"

if [[ ! -f "$CRATE_PATH/Cargo.toml" ]]; then
  echo "Error: No Cargo.toml found at $CRATE_PATH" >&2
  exit 1
fi

CRATE_NAME=$(grep '^name' "$CRATE_PATH/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')

# Helper: grep that returns 0 even on no match (safe for pipefail)
grepq() { grep "$@" || true; }

cat <<EOF
## Crate Map: \`$CRATE_NAME\`

> Auto-generated by \`scripts/crate-map.sh $CRATE_DIR\`

EOF

# ── 1. Dependency Graph ──────────────────────────────────────────────────────

echo "### Dependency Graph"
echo ""

cd "$REPO_ROOT/codex-rs"

echo "#### Depends on (workspace crates)"
echo '```'
cargo tree -p "$CRATE_NAME" --depth 1 -e normal 2>/dev/null \
  | tail -n +2 \
  | sed 's/ (proc-macro)//; s/ v[0-9].*//' \
  | sed 's/[├└│─]//g; s/^ *//' \
  | grepq -E 'orbit-code|_test_support' \
  | sort -u
echo '```'
echo ""

echo "#### Depended on by"
echo '```'
ALL_CRATES=$(cargo tree --workspace --depth 0 -e normal 2>/dev/null | awk '{print $1}')
found_any=false
for other in $ALL_CRATES; do
  [[ "$other" == "$CRATE_NAME" ]] && continue
  if cargo tree -p "$other" --depth 1 -e normal 2>/dev/null | tail -n +2 | grep -q "$CRATE_NAME"; then
    echo "$other"
    found_any=true
  fi
done
if [[ "$found_any" == "false" ]]; then
  echo "(none — this is a leaf crate)"
fi
echo '```'
echo ""

# ── 2. Module Tree ───────────────────────────────────────────────────────────

cd "$CRATE_PATH"

ENTRY=""
for candidate in src/lib.rs src/main.rs; do
  [[ -f "$candidate" ]] && ENTRY="$candidate" && break
done

if [[ -n "$ENTRY" ]]; then
  echo "### Module Tree"
  echo '```'
  echo "# Legend: ▸ = pub, (indent) = private"
  grepq -E "^(pub )?mod " "$ENTRY" \
    | sed 's/pub mod /▸ /; s/mod /  /; s/;//; s/ {.*//' \
    | sort

  for modfile in src/*/mod.rs; do
    [[ -f "$modfile" ]] || continue
    parent=$(dirname "$modfile" | sed 's|src/||')
    grepq -E "^(pub )?mod " "$modfile" \
      | sed "s/pub mod /  ▸ ${parent}::/; s/mod /    ${parent}::/; s/;//; s/ {.*//" \
      | sort
  done
  echo '```'
  echo ""
fi

# ── 3. Public API Surface ────────────────────────────────────────────────────

echo "### Public API Surface"
echo ""

if [[ -n "$ENTRY" ]]; then
  REEXPORTS=$(grepq -c "^pub use " "$ENTRY")
  if [[ "$REEXPORTS" -gt 0 ]]; then
    echo "#### Re-exports ($REEXPORTS items from lib.rs)"
    echo '```rust'
    grepq "^pub use " "$ENTRY"
    echo '```'
    echo ""
  fi
fi

echo "#### Key Types"
echo '```'
grepq -rn "^pub struct\|^pub enum\|^pub trait" src/ --include="*.rs" \
  | grepq -v '_tests\.rs' \
  | sed 's|src/||; s/ {$//; s/ {//; s/ where$//' \
  | sort
echo '```'
echo ""

echo "#### Key Functions"
echo '```'
grepq -rn "^pub fn\|^pub async fn\|^pub const " src/ --include="*.rs" \
  | grepq -v '_tests\.rs' \
  | sed 's|src/||; s/ {$//' \
  | sort
echo '```'
echo ""

# ── 4. Test Map ──────────────────────────────────────────────────────────────

echo "### Test Map"
echo ""

UNIT_TESTS=$(find src/ -name "*_tests.rs" 2>/dev/null | sort)
if [[ -n "$UNIT_TESTS" ]]; then
  echo "#### Unit Test Files"
  echo '```'
  while IFS= read -r f; do
    count=$(grepq -c "#\[test\]\|#\[tokio::test\]" "$f")
    printf "%-60s %3s tests\n" "$f" "$count"
  done <<< "$UNIT_TESTS"
  echo '```'
  echo ""
fi

INLINE_TESTS=$(grepq -rl "#\[cfg(test)\]" src/ --include="*.rs" | grepq -v '_tests\.rs' | sort)
if [[ -n "$INLINE_TESTS" ]]; then
  echo "#### Files with inline #[cfg(test)] modules"
  echo '```'
  echo "$INLINE_TESTS"
  echo '```'
  echo ""
fi

if [[ -d tests/ ]]; then
  INT_TESTS=$(find tests/ -name "*.rs" 2>/dev/null | sort)
  if [[ -n "$INT_TESTS" ]]; then
    echo "#### Integration Tests"
    echo '```'
    while IFS= read -r f; do
      count=$(grepq -c "#\[test\]\|#\[tokio::test\]" "$f")
      printf "%-60s %3s tests\n" "$f" "$count"
    done <<< "$INT_TESTS"
    echo '```'
    echo ""
  fi
fi

TOTAL=$(grepq -rc "#\[test\]\|#\[tokio::test\]" src/ tests/ --include="*.rs" \
  | awk -F: '{s+=$2} END {print s+0}')
echo "**Total: $TOTAL tests**"
echo ""

# ── 5. Call Graph ─────────────────────────────────────────────────────────────

echo "### Call Graph"
echo ""

# Find the main orchestration file
MAIN_MODULE=""
for candidate in src/codex.rs src/main.rs src/lib.rs; do
  [[ -f "$candidate" ]] && MAIN_MODULE="$candidate" && break
done

if [[ -n "$MAIN_MODULE" ]]; then
  echo "#### Entry Points (\`$(basename "$MAIN_MODULE")\`)"
  echo '```'
  grepq -n "^\s*pub async fn\|^\s*pub fn" "$MAIN_MODULE" \
    | sed 's/^\s*//; s/ {$//' \
    | head -30
  echo '```'
  echo ""

  echo "#### Internal Dispatch (module::function calls from \`$(basename "$MAIN_MODULE")\`)"
  echo '```'
  grepq -oE '\b[a-z][a-z_]+::[a-z_]+\(' "$MAIN_MODULE" \
    | sort -u \
    | grepq -vE '^(std|tokio|serde|tracing|anyhow|futures|io|env|path|fs|future|async_channel|iter|mem|oneshot|iana_time_zone|slice|task|time|super|self)::' \
    | sed 's/($//' \
    | head -60
  echo '```'
  echo ""
fi

# Cross-file references: which files call Session/CodexThread methods
echo "#### Cross-Module References (who calls Session/handlers)"
echo '```'

# Key dispatch targets — find which files reference the handlers module
for target in "handlers::" "Session::" "CodexThread::" "ToolRouter::" "ToolRegistry::"; do
  callers=$(grepq -rl "$target" src/ --include="*.rs" \
    | grepq -v '_tests\.rs' \
    | sed 's|src/||' \
    | sort -u \
    | tr '\n' ', ' \
    | sed 's/,$//')
  if [[ -n "$callers" ]]; then
    printf "%-25s ← %s\n" "$target" "$callers"
  fi
done
echo '```'
echo ""

echo "---"
echo "_Generated: $(date -u +%Y-%m-%d)_"
